### ISSUE TITLE
New tests fail if test user's account has no forms

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo_selenium_tests#5]
Something in [`delete_all_forms.py`](https://github.com/kobotoolbox/kobo_selenium_tests/blob/041b6d098eeb76f55e779ca3de51b3b075d4a3d1/new-selenium-tests/tests/delete_all_forms_test.py) fails if the test user's account does not have any forms. I observed this while trying to test a new server. The traceback is attached below. I worked around the problem by manually logging in as the Selenium user and creating a form.

```
09:46:22 Traceback (most recent call last):
09:46:22   File "/var/lib/jenkins/workspace/Base KoBo Selenium test/new-selenium-tests/tests/delete_all_forms_test.py", line 20, in delete_all_forms
09:46:22     self.assertTrue(self.is_element_present_with_wait(By.CSS_SELECTOR, form_link))
09:46:22   File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
09:46:22     raise self.failureException(msg)
09:46:22 AssertionError: False is not true
09:47:37 Traceback (most recent call last):
09:47:37   File "/var/lib/jenkins/workspace/Base KoBo Selenium test/new-selenium-tests/tests/delete_all_forms_test.py", line 20, in delete_all_forms
09:47:37     self.assertTrue(self.is_element_present_with_wait(By.CSS_SELECTOR, form_link))
09:47:37   File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
09:47:37     raise self.failureException(msg)
09:47:37 AssertionError: False is not true
09:47:37 F
09:47:37 ======================================================================
09:47:37 FAIL: test_step_00_run_all (__main__.Test_Selenium)
09:47:37 ----------------------------------------------------------------------
09:47:37 Traceback (most recent call last):
09:47:37   File "selenium_test_suite.py", line 209, in test_step_00_run_all
09:47:37     test_case_class.__dict__[current_test.get('test_method')](self)
09:47:37   File "/var/lib/jenkins/workspace/Base KoBo Selenium test/new-selenium-tests/tests/delete_all_forms_test.py", line 30, in delete_all_forms
09:47:37     self.handle_test_exceptions(e)
09:47:37   File "/var/lib/jenkins/workspace/Base KoBo Selenium test/new-selenium-tests/tests/empty_test.py", line 201, in handle_test_exceptions
09:47:37     raise e
09:47:37 AssertionError: False is not true
09:47:37 
09:47:37 ----------------------------------------------------------------------
09:47:37 Ran 1 test in 150.541s
09:47:37 
09:47:37 FAILED (failures=1)
09:47:37 <============ 1st SELENIUM TEST TRY ============>
09:47:37 Reached: test_login
09:47:37 HIT: https://kobo.stage.kobo.568elmp03.blackmesh.com/accounts/login/?next=/
09:47:37 PASSED: test_login
09:47:37 Reached: delete_all_forms
09:47:37 FAILED: delete_all_forms
09:47:37 An Exception of type <type 'exceptions.AssertionError'> happened while trying to create a delete_all_forms more info: 
09:47:37 Arguments: ('False is not true',)
09:47:37 Message: False is not true
09:47:37 <============ 2nd SELENIUM TEST TRY ============>
09:47:37 Reached: test_login
09:47:37 HIT: https://kobo.stage.kobo.568elmp03.blackmesh.com/accounts/login/?next=/
09:47:37 PASSED: test_login
09:47:37 Reached: delete_all_forms
09:47:37 FAILED: delete_all_forms
09:47:37 An Exception of type <type 'exceptions.AssertionError'> happened while trying to create a delete_all_forms more info: 
09:47:37 Arguments: ('False is not true',)
09:47:37 Message: False is not true
09:47:37 Removing Selenium server container.
09:47:37 4d04de8851c1ba2270d7fb7fab27d87549534db189106a59674483777a5e3711
09:47:37 Build step 'Execute shell' marked build as failure
09:47:37 Finished: FAILURE
```

**Comment by yahyazini** [comment]
This should be fixed as of 30e8cb8511f4f4af35bdce17572e7376375e0a3a
